name: Deploy Solana Contracts

on:
  push:
    branches: [ main ]
    paths:
      - 'solana/**'
      workflow_dispatch:  # Add this line to enable manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Install Solana CLI
        run: |
          sh -c "$(curl -sSfL https://release.solana.com/v1.14.17/install) "
          export PATH="/home/runner/.local/share/solana/install/active_release/bin:$PATH"
          solana --version
          
      - name: Setup Anchor
        run: |
          npm install -g @project-serum/anchor
          anchor --version
          
      - name: Setup Solana Wallet
        run: |
          mkdir -p ~/.config/solana
          echo "${{ secrets.SOLANA_KEYPAIR }}" > ~/.config/solana/id.json
          solana config set --url https://api.devnet.solana.com
          solana config set --keypair ~/.config/solana/id.json
          
      - name: Build and Deploy
        working-directory: ./solana/token-factory
        run: |
          npm install
          anchor build
          anchor deploy --provider.cluster devnet
          
      - name: Save Program ID
        run: |
          PROGRAM_ID=$(solana address -k ./solana/token-factory/target/deploy/token_factory-keypair.json) 
          echo "Deployed Program ID: $PROGRAM_ID"
          echo "SOLANA_PROGRAM_ID=$PROGRAM_ID" >> $GITHUB_ENV
          
      - name: Update Connector.js
        run: |
          sed -i "s/const SOLANA_PROGRAM_ID = \".*\"/const SOLANA_PROGRAM_ID = \"$SOLANA_PROGRAM_ID\"/" ./integration/connector.js
          
      - name: Commit Updated Connector
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update Solana Program ID in connector.js [skip ci]"
          file_pattern: integration/connector.js
