name: Deploy Ethereum Contracts

on:
  workflow_dispatch:  # Manual trigger only for simplicity

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Debug - List Repository Contents
        run: |
          echo "Repository root contents:"
          ls -la
          echo "Checking for ethereum directory:"
          ls -la ethereum || echo "ethereum directory not found"
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Install Truffle
        run: npm install -g truffle
        
      - name: Check if ethereum directory exists
        id: check_ethereum
        run: |
          if [ -d "./ethereum" ]; then
            echo "ethereum_exists=true" >> $GITHUB_OUTPUT
          else
            echo "ethereum_exists=false" >> $GITHUB_OUTPUT
            echo "Ethereum directory does not exist. Please create it first."
            exit 1
          fi
        
      - name: Install Dependencies
        if: steps.check_ethereum.outputs.ethereum_exists == 'true'
        working-directory: ./ethereum
        run: npm install
        
      - name: Create .env file
        if: steps.check_ethereum.outputs.ethereum_exists == 'true'
        working-directory: ./ethereum
        env:
          MNEMONIC: ${{ secrets.ETHEREUM_MNEMONIC }}
          INFURA_KEY: ${{ secrets.INFURA_API_KEY }}
        run: |
          echo "MNEMONIC=${MNEMONIC}" > .env
          echo "INFURA_API_KEY=${INFURA_KEY}" >> .env
          
      - name: Deploy Contracts
        if: steps.check_ethereum.outputs.ethereum_exists == 'true'
        working-directory: ./ethereum
        run: |
          truffle migrate --network sepolia > deployment_output.txt || echo "Deployment failed, but continuing for debugging"
          cat deployment_output.txt
          
      - name: Display Contract Addresses
        if: steps.check_ethereum.outputs.ethereum_exists == 'true'
        working-directory: ./ethereum
        run: |
          echo "Searching for contract addresses in deployment output..."
          grep -A 1 "contract address:" deployment_output.txt || echo "No contract addresses found in output"
          echo "If addresses are not shown above, check the full deployment logs."
